### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by Fl414r** [FrenzyYum/GenshinWishingBot#2]

**Comment by FrenzyYum** [comment]
Please specify what you mean. Instructions are [here](https://github.com/FrenzyYum/GenshinWishingBot#installation). This is a basic .NET Core Console Application, you may want to research how to build/run/publish it with CLI tools or Visual Studio.
Note that you can't run it with serverless functions such as Heroku since they don't work with SQLite at all.

**Comment by Fl414r** [comment]
I ran it and it even works in private chat (/start and /help), as long as I don't add it to the public chat. When I write a command in the public chat, it says this:
```
Error: SQL logic error
no such table: Chats
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at TelegramUI.Commands.Language.AddChat(Message message) in c:\Users\Fl414r\Documents\GitHub\GenshinWishingBot\src\TelegramUI\Commands\Language.cs:line 20
   at TelegramUI.Telegram.TelegramCommands.BotOnMessage(Object sender, MessageEventArgs e) in c:\Users\Fl414r\Documents\GitHub\GenshinWishingBot\src\TelegramUI\Telegram\TelegramCommands.cs:line 76

Entity: {
  "MessageId": 45,
  "From": {
    "Id": /numbers here/,
    "FirstName": "Fl414r",
    "Username": "Fl414r",
    "LanguageCode": "ru"
  },
  "Date": "2022-03-25T14:12:40Z",
  "Chat": {
    "Id": -1001404233428,
    "Type": 3,
    "Title": "Is this a test"
  },
  "Text": "/wish",
  "Entities": [
    {
      "Type": 2,
      "Length": 5
    }
  ],
  "EntityValues": [
    "/wish"
  ],
  "Type": 1
}
```

**Comment by FrenzyYum** [comment]
Yeah, my bad. For some reason, I presumed that the schema would auto-create. Please pull [the latest change](https://github.com/FrenzyYum/GenshinWishingBot/commit/559a442efd1cad4b23574c1d7d848e36ed7ac986) and try again.

**Comment by Fl414r** [comment]
Thanks all work!
